from circle import Circle 
from rectangle import Rectangle
from square import Square
from triangle import Triangle

aylana=Circle(8)
b=aylana.is_valid()
c=aylana.diameter()
d=aylana.circumference()
e=aylana.area()
print(b)
print(c)
print(d)
print(e)
turtburchak=Rectangle(5,6)
a=turtburchak.is_valid()
r=turtburchak.perimeter()
t=turtburchak.area()
print(a)
print(r)
print(t)
kvadrat=Square(4)
z=kvadrat.is_valid()
x=kvadrat.area()
n=kvadrat.perimeter()
print(z)
print(x)
print(n)
uchburchak=Triangle(7,5,8)
a=uchburchak.is_valid()
b=uchburchak.perimeter()
c=uchburchak.area()
print(a)
print(b)
print(c)